#! /bin/sh

set -e

DATE=20230121
FILE=adafruit-circuitpython-bundle-8.x-mpy-${DATE}
DIR=/Volumes/CIRCUITPY

curl -L https://github.com/adafruit/Adafruit_CircuitPython_Bundle/releases/download/20230121/${FILE}.zip >bundle.zip
unzip bundle.zip
rm -rf bundle bundle.zip
mv ${FILE} bundle

rm -rf ${DIR}/lib/*

for m in $(cat module_requirements); do
  if [ -d "bundle/lib/${m}" ]; then
    cp -R bundle/lib/${m} ${DIR}/lib
  else
    cp bundle/lib/${m}.mpy ${DIR}/lib
  fi
done
